version: "3"

services:
  postgresdb:
    image: 'postgres:10-alpine'
    container_name: microservice_db
    environment:
      POSTGRES_DB: microservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    expose:
      - '5432'
    restart: 'unless-stopped'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d microservice -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5